# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Houndstooth
email: 'info@bowtie.co'
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://houndstootheditor.co" # the base hostname & protocol for your site, e.g. http://example.com

logourl: /assets/images/houndstooth-logo.png # Site logo
navlogourl: /assets/images/houndstooth-logo.png # nav logo
author: "⋈ Bowtie.co"

# Theme additions

mailchimp_username: bowtie
mailchimp_server: us5
mailchimp_apikey: 85cc3923dcbe51832fa566843
mailchimp_listid: d4c3230a3a

google_analytics_id:  "UA-112855270-3" # Your google analytics ID (e.g. 'UA-XXXXXXXX-X')
google_tag_manager:  "GTM-TK6JBBR" # Your google analytics ID (e.g. 'UA-XXXXXXXX-X')
google_api_key: 'AIzaSyDJY4oywMOWRYa8btinlU2LCOzQ8vX13go' # Your Google API key for Maps


bowtietheme:
  # Contact info, leave blank to ignore
  contact:
    company: ⋈ Bowtie.co
    address: 3575 Ringsby Court, STE 302
    city: Denver
    state: CO
    zip: 80216
    country: USA
    phone: (720) 504-8091
    latlng: 39.773771,-104.9827857,17z # (e.g. '39.733536,-104.992611')
  social:
    twitter: bowtie_co # (e.g. 'bowtie_co')
    facebook: bowtieagency # (e.g. 'bowtieagency')
    github: bowtie-co # (e.g. 'bowtie-io')
    instagram: bowtieagency # (e.g. 'bowtieagency')
    flickr: #groups/2772799@N24/ # (e.g. 'groups/2772799@N24/')
    linkedin: company/bowtie/ # (e.g. 'company/bowtie')
    youtube: #channel/UCovWO5keLOLcLu8WdO-ABJw # (e.g. 'channel/UCovWO5keLOLcLu8WdO-ABJw')

collections_dir: content

collections:
  sections:
    output: false
  features:
    output: false
    permalink: /:path/
  posts:
    output: true
    permalink: /usage/:path/
  team:
    output: false
    permalink: /:path/

permalink: /:categories/:title/
relative_permalinks: false


# Server Config options
livereload: false     # You no longer need to include --livereload
reload_port: 5000    # If you don't want to use the default port
carousel-speed: 5000 #set speed for all image sliders

#toggle future post dates back on
future: true

#compress sass
sass:
  sass_dir: /assets/_sass


# Build settings
# markdown: kramdown
# kramdown:
#   syntax_highlighter: false
#   syntax_highlighter_opts:
#     disable : true
theme:
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .gitignore
  - .sass-cache
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
